require:
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
#-------------------------------------------------------------------------------
RSpec/ExampleLength:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
RSpec/FilePath:
  Exclude:
    - spec/register_transformer_psc.rb
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
RSpec/MessageSpies:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
RSpec/NamedSubject:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
    - spec/unit/bods_mapping/person_statement_spec.rb
RSpec/NestedGroups:
  Exclude:
    - spec/unit/bods_mapping/interest_parser_spec.rb
RSpec/StubbedMock:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
RSpec/VerifiedDoubles:
  Exclude:
    - spec/unit/bods_mapping/child_entity_statement_spec.rb
    - spec/unit/bods_mapping/entity_statement_spec.rb
    - spec/unit/bods_mapping/interest_parser_spec.rb
    - spec/unit/bods_mapping/ownership_or_control_statement_spec.rb
