name: register
networks:
  elasticsearch: {}
  redis: {}
  transformer: {}
services:
  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      xpack.security.enabled: "false"
    healthcheck:
      interval: 5s
      retries: 6
      start_period: 60s
      test:
        - CMD
        - curl
        - -fs
        - http://localhost:9200/_cluster/health
    image: docker.io/library/elasticsearch:8.12.0
    networks:
      - elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  redis:
    healthcheck:
      interval: 5s
      retries: 6
      start_period: 60s
      test:
        - CMD
        - redis-cli
        - PING
    image: docker.io/library/redis:7
    networks:
      - redis
    volumes:
      - redis:/data
  transformer-psc:
    build:
      context: .
      target: dev
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    networks:
      - elasticsearch
      - redis
      - transformer
    volumes:
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_COMMON:-.dockerempty}:/home/x/lib/register-common
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_SOURCES_BODS:-.dockerempty}:/home/x/lib/register-sources-bods
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_SOURCES_OC:-.dockerempty}:/home/x/lib/register-sources-oc
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_SOURCES_PSC:-.dockerempty}:/home/x/lib/register-sources-psc
      - ./.rubocop.yml:/home/x/r/.rubocop.yml
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./bin:/home/x/r/bin
      - ./lib:/home/x/r/lib
      - ./register_transformer_psc.gemspec:/home/x/r/register_transformer_psc.gemspec
      - ./spec:/home/x/r/spec
version: "3.8"
volumes:
  elasticsearch: {}
  redis: {}
