version: "3.8"
services:
  transformer-psc:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - transformer
    restart: on-failure
    volumes:
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_COMMON:-.dockerempty}:/home/x/lib/register-common
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_SOURCES_BODS:-.dockerempty}:/home/x/lib/register-sources-bods
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_SOURCES_OC:-.dockerempty}:/home/x/lib/register-sources-oc
      - ${DC_TRANSFORMER_PSC_LIB_REGISTER_SOURCES_PSC:-.dockerempty}:/home/x/lib/register-sources-psc
      - ./bin:/home/x/r/bin
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_transformer_psc.gemspec:/home/x/r/register_transformer_psc.gemspec
      - ./spec:/home/x/r/spec
      - ./statements:/home/x/r/statements
networks:
  elasticsearch: {}
  transformer: {}
