version: "3.8"
services:
  transformer-psc:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - transformer
    restart: on-failure
    volumes:
      - ./bin:/home/x/r/bin
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_transformer_psc.gemspec:/home/x/r/register_transformer_psc.gemspec
      - ./spec:/home/x/r/spec
      - ./statements:/home/x/r/statements
      #- ../register-common:/home/x/r/lib/register-common
      #- ../register-sources-bods:/home/x/r/lib/register-sources-bods
      #- ../register-sources-oc:/home/x/r/lib/register-sources-oc
      #- ../register-sources-psc:/home/x/r/lib/register-sources-psc
networks:
  elasticsearch: {}
  transformer: {}
