version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cp .env.example .env
            docker compose build
      - run:
          name: Test
          command: |
            docker compose run transformer-psc test
