version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build dev
          command: |
            docker build --target dev -t dev .
      - run:
          name: Test
          command: |
            function run() { docker run --rm -t --env-file .env.circleci dev "$@"; }
            run bin/test
