version: 2.1
jobs:
  build:
    parallelism: 1
    working_directory: ~/openownership/register-transformer-psc

    docker:

      - image: cimg/ruby:3.1.2-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

      - image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
        environment:
          - 'discovery.type=single-node'
          - 'cluster.name=register-transformer-psc-elasticsearch'
          - 'bootstrap.memory_lock=true'
          - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'

    steps:

      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - app-bundle-v3-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: app-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for ElasticSearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m

      - run:
          command: bundle exec rspec
          environment:
            TEST: 1
            BODS_AWS_REGION: eu-west-1
            BODS_AWS_ACCESS_KEY_ID: key1
            BODS_AWS_SECRET_ACCESS_KEY: secret1
            BODS_S3_BUCKET_NAME: fakebucket
            ELASTICSEARCH_HOST: localhost
            # ELASTICSEARCH_PASSWORD:
            ELASTICSEARCH_PORT: 9200
